## ----global_options, include=FALSE----------------------------------------------------------------------------------
library(knitr)
knitr::opts_chunk$set(dpi = 100, echo= TRUE, warning=FALSE, message=FALSE, fig.align = 'center',
                      fig.show=TRUE, fig.keep = 'all', out.width = '90%')


## -------------------------------------------------------------------------------------------------------------------
library(mixOmics)


## -------------------------------------------------------------------------------------------------------------------
data(liver.toxicity) # call liver toxicity dataset
X <- liver.toxicity$gene # extract gene expression data
dim(X) # confirm the dimension of data


## ---- fig.cap= "FIGURE 1: Histogram depicting the distribution of p-values generated by running a Shaprio-Wilk test on each feature in the liver toxicity gene dataset. The large value <0.05 indicates that there are many features which are significanly unlikely to be distributed normally."----
p.values = c() # initialise empty list to carry p-values

# for each column of the dataframe, undergo a shapiro-wilk test and extract the p-value
for (col in 1:dim(X)[2]) { 
  p.values[col] <- shapiro.test(X[, col])$p.value
}

h <- hist(p.values, breaks = 20, plot = FALSE) # create the histogram object
h$density <- h$counts/sum(h$counts) # adjust the frequency to a density
plot(h,freq=FALSE, ylim = c(0, 0.5)) # plot the histogram


## ---- fig.cap= "FIGURE 2: Explained variance of Independent Principal Components on the Liver Toxicity Gene data"----
toxic.sipca <- sipca(X, ncomp = 10) # run preliminary model
plot(toxic.sipca) # plot the explained variance per component


## ---- fig.cap = "FIGURE 3: Kurtosis values of Independent Principal Components on the Liver Toxicity Gene data"-----
barplot(toxic.sipca$kurtosis, ylim = c(0, 32), names.arg = seq(1, 10, 1), xlab = "Independent Principal Components", ylab = "Kurtosis value")


## -------------------------------------------------------------------------------------------------------------------
final.sipca <- sipca(X, ncomp = 3) # based off figure 3, three components is best
                                   # using the default keepX, c(50, 50, 50) in this case


## ---- fig.show = "hold", out.width = "49%", fig.cap = "FIGURE 4: Sample plot from the sPCA (a) and sIPCA (b) performed on the liver toxicity gene data."----
final.spca <- spca(X, ncomp = 3, scale = TRUE, keepX = final.sipca$keepX) # generate sPCA on same dataset

plotIndiv(final.spca, comp = c(1, 2), ind.names = TRUE, # plot the samples of sPCA
          title = '(a) Liver Toxicity Genes, sPCA comp 1 - 2')

plotIndiv(final.sipca, comp = c(1, 2), ind.names = TRUE, # plot the samples of sIPCA
          title = '(b) Liver Toxicity Genes, sIPCA comp 1 - 2')


## ---- fig.cap = "FIGURE 5: Correlation circle plot from the sIPCA performed on the Liver Toxicity genedata. Only the gene genes selected by the sIPCA are shown on this plot."----
plotVar(final.sipca, comp = c(1, 2), var.names = FALSE,  # plot features against the sIPCA components
        title = 'Liver Toxicity Genes, sIPCA comp 1 - 2')

