---
title: "Not sure yet"
output: html_document
---

```{r global_options, include=FALSE}
library(knitr)
knitr::opts_chunk$set(dpi = 100, 
                      echo= TRUE, 
                      warning=FALSE, 
                      message=FALSE, 
                      fig.show=TRUE, 
                      fig.keep = 'all',
                      out.width = "70%")
```

# Yeet

``` {r}
library(mixOmics) # import the mixOmics library

load('Data/nmt_data_processed.RData') # load the gastrulation data

X1 <- data$rna # select the five dataframes to explore
X2 <- data$met_genebody
X3 <- data$acc_genebody
X4 <- data$met_promoter
X5 <- data$acc_promoter

# compile these into a single X object
X <- list(rna = X1, met.gene = X2, acc.gene = X3,
          met.pro = X4, acc.pro = X5) 

lapply(X, dim) # check dimensions
```

```{r}
# for square matrix filled with 0.5s
design = matrix(0.5, ncol = length(X), nrow = length(X), 
                dimnames = list(names(X), names(X)))
diag(design) = 0 # set diagonal to 0s

choice.ncomp <- 3 
choice.keepX <- list(rna = rep(50, 3), # 50 features per each component 
                     met.gene = rep(50, 3), 
                     acc.gene = rep(50, 3),
                     met.pro = rep(50, 3), 
                     acc.pro = rep(50, 3))

final.mbspls.model = block.spls(X, indY = 1,  
                                ncomp = choice.ncomp, 
                                keepX = choice.keepX,
                                design = design)
```

``` {r, out.width = "90%", fig.align = "center"}
plotIndiv(final.mbspls.model, ind.names = FALSE,
          group = as.factor(cell_metadata$lineage), 
          pch = as.factor(cell_metadata$stage),
          col.per.group = color.mixo(1:8), 
          legend = TRUE, legend.title = 'Lineage', legend.title.pch = 'Stage',
          blocks = 1)
```

``` {r, echo = FALSE}
set.seed(422)

samples <- sample(1:dim(data$rna)[1], 30)

X1.a <- data$rna[samples, ] 
X2.a <- data$met_genebody[samples, ] 
X3.a <- data$acc_genebody[samples, ] 
X4.a <- data$met_promoter[samples, ] 
X5.a <- data$acc_promoter[samples, ] 
X.arrow <- list(rna = X1.a, met.gene = X2.a, acc.gene = X3.a,
          met.pro = X4.a, acc.pro = X5.a) 

final.mbspls.model.arrow = block.spls(X.arrow, indY = 1, 
                                ncomp = choice.ncomp, 
                                keepX = choice.keepX,
                                design = design)
```

``` {r, out.width = "90%", fig.align = "center"}
symbols <- list(rna = 1, met.gene = 6, acc.gene = 7, met.pro = 10, acc.pro = 9)

plotArrow(final.mbspls.model.arrow, ind.names = FALSE,
          group = as.factor(cell_metadata$lineage[samples]),
          pch = symbols, pch.size = 3)
```

``` {r, out.width = "90%", fig.align = "center"}
plotVar(final.mbspls.model, var.names = FALSE,
        legend = TRUE, cutoff = 0.5,
        pch = c(0,1,2,3,4))
```

